[package]
name = "orhunca"
version = "0.5.0"
edition = "2021"
description = "Orhunca: Türkçe tabanlı programlama dili ve derleyicisi"
repository = "https://github.com/furkan003/orhunca"

[[bin]]
name = "orhunca"
path = "src/main.rs"

[dependencies]
cranelift-codegen = "0.136"
cranelift-frontend = "0.136"
cranelift-module = "0.136"
cranelift-object = "0.136"
cranelift-native = "0.136"
target-lexicon = "0.13"
serde_json = "1"
wasm-encoder = "0.261"
object = { version = "0.40", default-features = false, features = ["read_core", "elf", "coff", "std"] }

[dev-dependencies]
wasmparser = "0.261"

[profile.release]
opt-level = 3
