blank_issues_enabled: false
contact_links:
  - name: Güvenlik açığı bildir
    url: https://github.com/Furkan003/Orhunca/security/advisories/new
    about: Güvenlik açıklarını lütfen gizli olarak bildirin
